### ISSUE TITLE
install instructions documentation

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/gluster_integration#10]
There should be document which describes:
- what software should be installed and how should be configured before installing Tendrl
- Tendrl installation process
- Tendrl post installation steps like configuration, service starting and so on

[was originally at https://tendrl.atlassian.net/browse/TEN-36]

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/gluster_integration/blob/master/doc/source/installation.rst
and

https://github.com/Tendrl/documentation/blob/master/deployment.adoc

I can re-open this if above docs dont solve the issue
