### ISSUE TITLE
Some bugs identified from pytest

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/gluster_integration#29]
1. Inside file servers.py a variable **name** takes two values (**name** = 'clusters/gluster/%s/peers/%s') but Inside all render function only one value is assigned to that variable
   ( self.**name** % self.peer_uuid).

2.From rpc.py,  a while loop is running without any check in _acceptor method. I cant test that function.
and control never come out from that function.

3.From ini2json.py, there a method called dget it is not called anywhere and object for class StrictConfigParser is created and initialized and destroyed inside method ini_to_dict so calling dget from other method is useless.

**Comment by r0h4n** [comment]
Is this fixed?

**Comment by GowthamShanmugam** [comment]
@r0h4n This bug already fixed we can close this

**Comment by sankarshanmukhopadhyay** [comment]
As per comment above, closing the issue until it is observed again.
