### ISSUE TITLE
For testing Tox required bridge_common as site-package

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/gluster_integration#37]
For testing gluster_bridge, tox required bridge_common as site-package, we have to give bridge_common in test_requirement as pip installable. 

refs : https://gist.github.com/GowthamShanmugam/bf66174d7d6062fab936706c713d3d0c

**Comment by r0h4n** [comment]
Checkout https://github.com/Tendrl/gluster_bridge/pull/38

**Comment by r0h4n** [comment]
Please let me know if this is done

**Comment by GowthamShanmugam** [comment]
@r0h4n This bug is already fixed, we can close this

**Comment by sankarshanmukhopadhyay** [comment]
Closing the issue as per comment above. I'd request that such issues are closed as and when addressed rather than kept open.
