### ISSUE TITLE
Reading jobs from etcd doesnt adhere to the api job structure

### ISSUE THREAD

**Issue by shtripat** [Tendrl/gluster_integration#40]
The new job structure is as per https://github.com/Tendrl/bridge_common/blob/master/etc/samples/tendrl_api_job.sample.json.

Based on this rpc.py which reads and processes the jobs from etcd job queue should be modified to figure out the actual flow name and invoke the same.

**Comment by shtripat** [comment]
I strongly feel we should refer a flow only from API job which can internally invoke multiple atoms based on its need. Flows can be more flexibly defined with different combinations of atoms for different api needs.

**Comment by sankarshanmukhopadhyay** [comment]
This has been open and under consideration for a month (ish) now - what's the decision? @r0h4n

**Comment by shtripat** [comment]
This is done in previous hackthon. @r0h4n can you please confirm and close this?

**Comment by r0h4n** [comment]
This one has gone through many iterations and is stable now. More details https://github.com/Tendrl/common/blob/master/etc/samples/tendrl_api_job.sample.json
