### ISSUE TITLE
check_commit_msg.py displays a misleading error message

### ISSUE THREAD

**Issue by anmolbabu** [Tendrl/gluster_integration#80]
The check_commit_msg.py complains that the commis message should be of the form :

'tendrl-bug-id:<tendrl_repo>/issue_id'

It should probably say :

tendrl-bug-id:Tendrl/<tendrl_repo_name>#<issue_id>

**Comment by GowthamShanmugam** [comment]
@anmolbabu Tendrl-bug-id : should be <tendrl_repo>#issue_id, Then only a commit will be updated in issue page
