### ISSUE TITLE
[packaging] move list of python project from requirements.txt into install_requires in setup.py

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/gluster_integration#98]
This issue suggest to remove `requirements.txt` file and move items which this file contains into `install_requires` setuptools keyword in `setup.py` file.

## Reasoning

Based on [explanation of difference between `install_requires` keyword and `requirements.txt` file](https://packaging.python.org/requirements/#install-requires-vs-requirements-files) from upstream [Python Packaging User Guide](https://packaging.python.org/), I understand that:

* python project *should* provide minimal abstract list of projects which are needed to run it correctly in [`install_requires`](https://packaging.python.org/distributing/#install-requires)
* [`requirements.txt` files](https://pip.pypa.io/en/latest/user_guide/#requirements-files) are used to define the requirements for a complete python environment

Since this project is a single Tendrl component, which is expected to be installed with other Tendrl components together, using requirement file seems to be inappropriate. Listing dependencies of single reusable python library/tool/daemon, which is our case here, is not mentioned among 4 common uses of Requirements files as listed in [description of the feature in packaging guide](https://pip.pypa.io/en/latest/user_guide/#requirements-files). Moreover, it creates additional issues:

* using `requirements.txt` file makes us to install the project in non-production way, which means that we will find problems with listing requirements later than we should, see eg. issue https://github.com/Tendrl/performance_monitoring/issues/17 - this is very blatant issue, but was not noticed by any developer, unit tests or CI - since all of those are using installation method which doesn't resemble what an admin using this project would do
* keeping `requirements.txt` file while specifying `install_requires` in `setup.py` requires to maintain function to read `requirements.txt` file in `setup.py`, which is unnecessary maintenance burden
* feature set of `requirements.txt` is higher and includes features which should not be done in production setup

**Comment by r0h4n** [comment]
We are using "install_requires", check https://github.com/Tendrl/gluster_integration/blob/master/setup.py#L22

**Comment by mbukatov** [comment]
This issue was closed based on agreement described in https://github.com/Tendrl/alerting/issues/18#issuecomment-270661999 (keep requirements.txt file).
